title       = "sinablog"
baseURL     = "https://sinablog-cli.tamnd.com/"
description = "A command line for Sina Blog."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/sinablog-cli"
